---
title: "Sejam bem vindos"
description: |
  Primeiro contato com os alunos
author:
  - name: Dirceu S. Reis Jr.
date: 2022-05-31
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Prezados alunos de Transferência de Energia e Massa,

Se vocês estão lendo esta prmeira postagem de boas vindas do blog antes da primeira aula é porque vocês receberam meu email com instruções para entrar aqui. Mas se vocês estão lendo esta mensagem depois da primeira aula, não tem problema nenhum. O importante é que vocês acharam a página, que é uma novidade para este semestre.

Decidi criar esta página recentemente, pois penso que pode ser melhor do que o Aprender3 no longo prazo. Primeiro porque esta página extrapola a Universidade de Brasília, enquanto que o Aprender3 retringe o material apenas para os aunos da UnB. Mas isso não é o principal. No longo prazo, pretentdo desenvolver um material didático que complementará os livros, que já são muito bons, diga-se de passagem. Mas para dar aula, às vezes sinto falat de um material mais pessoal, escrito por mim mesmo.

Mas este é um período de transição. Trabalharei neste site ao longo dos próximos semestres. E como estamos num período de transição, pretendo continuar utlizando o Aprender3, pelo menos para disponibiizar e corrigir as listas de exercícios.  De resto, pretendo fazer por aqui.

Acabei esquecendo de me apresentar a vocês. Meu nome é Dirceu Reis e eu serei o professor da disciplina. Nós teremos nossa primeira conversa no primeiro dia de aula, na sala CT-43-15, no horário da disciplina. Estou animado. A última vez que estive presente numa sala de aula para dar aula foi há quase trÊs anos atrás. Além do período de aulas remotas por causa da pandemia, eu ainda havia tirado um ano sabático entre agosto de 2019 e julho de 2020, de modo que não entro numa sala há bastante tempo. Espero que vocês também estejam animados com esse retorno às salas de aula.

Nos vemos no dia 06 de Junho no horário da aula. 

Saudações,

Dirceu Reis


